# Generated by Django 6.0.3 on 2026-03-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=254)),
                ('description', models.TextField(default='', max_length=2000)),
                ('link', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='number',
            field=models.CharField(default='00', max_length=254),
        ),
    ]
