# Generated by Django 6.0.3 on 2026-04-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_password_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='facebook_link',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.categore'),
            preserve_default=False,
        ),
    ]
