# Generated by Django 6.0.3 on 2026-04-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_categore_clients_facebook_link_project_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.categore'),
        ),
    ]
