# Generated by Django 6.0.3 on 2026-04-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categorie',
            new_name='categore',
        ),
    ]
