# Generated by Django 6.0.3 on 2026-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_categorie_project_categore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categore',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
