# Generated by Django 6.0.3 on 2026-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_categore_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
